# Generated by Django 6.1 on 2026-08-06 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/')),
                ('image_url', models.URLField(blank=True, help_text='Fallback image URL if no file uploaded')),
                ('price', models.DecimalField(decimal_places=2, help_text='Original / MRP price', max_digits=10)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, help_text='Discounted price shown to customers. Leave blank if no offer.', max_digits=10, null=True)),
                ('stock', models.PositiveIntegerField(default=10)),
                ('rating', models.DecimalField(decimal_places=1, default=4.0, max_digits=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['id', 'slug'], name='products_pr_id_a08e3c_idx')],
            },
        ),
    ]
